name = "discussions"
type = "javascript"
zone_id = ""
account_id = "cc37374fdf8460487f00ac4cece37175"
route = "discussions"
workers_dev = true
compatibility_date = "2022-01-26"

# [secrets]
# WEBHOOK_URL

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
